Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
